# Generated by Django 4.2.4 on 2023-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSimilarImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_image", models.CharField(max_length=150)),
                ("similar_images", models.CharField(max_length=200)),
            ],
        ),
    ]
